name: Kiss Diff
description: Keeps It Simple Stupid Diff check, returns a set of true/false values for the diff state of a file or folder.
author: mudlabs
branding:
  icon: copy
  color: yellow
runs:
  using: node12
  main: action.js
inputs:
  path:
    description: The path of the file or folder to diff.
  token:
    description: PAT for authorisation.
    required: false
    default: ${{ github.token }}
outputs:
  added:
    description: Specifies the item was added.
  modified:
    description: Specifies the item was modified.
  removed:
    description: Specifies the item was removed.
  renamed:
    description: Specifies the item was renamed.
  name:
    description: Specifies the item name.
