name: Test Diff

on:
  push:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Simple Diff
        id: diff
        uses: ./
        with:
          path: "Funding(9th edition).xml"
          strict: false
      - run: |
          echo "${{ steps.diff.outputs.added }}"
          echo "${{ steps.diff.outputs.modified }}"
          echo "${{ steps.diff.outputs.removed }}"
          echo "${{ steps.diff.outputs.renamed }}"
          echo "${{ steps.diff.outputs.name }}"
